### ISSUE TITLE
run two 7-segment displays at once that do different things

### ISSUE THREAD

**Issue by swans123** [Seeed-Studio/Grove_4Digital_Display#13]
hi i wasnt sure how to get two different 4 segment displays to do different things at the same time i think i would just need to define them differently at the start and use different output pins but cant seem to get it thanks

**Comment by Combinacijus** [comment]
```
// Note that pin 6 and 9 is PWM pin but it shouldn't matter either way (try just in case)
TM1637 display1(6, 7);
TM1637 display2(9, 8); 
// Do your normal stuff
```
Checked source code and it's using [I2C bitbanging](https://github.com/Seeed-Studio/Grove_4Digital_Display/blob/dd7af58811e39a50e5cd08c5edab46d62e7864f1/TM1637.cpp#L190) without external libraries and both [clock and data pins are configurable on initialization](https://github.com/Seeed-Studio/Grove_4Digital_Display/blob/dd7af58811e39a50e5cd08c5edab46d62e7864f1/TM1637.cpp#L119). I don't see why it won't work (I might be missing something).
But if you already tried this please verify that both displays works separately on both pin configurations.

Also it would be nice if you post your code (edit original issue) that way it would be easier to debug problems or any mistakes thanks
