### ISSUE TITLE
clearDisplay hardcoded for 4 digits

### ISSUE THREAD

**Issue by ja518** [Seeed-Studio/Grove_4Digital_Display#15]
While most functions use the number of digits specified in DIGITS, clearDisplay writes 0x7f only to digits 0x00~0x03.
This creates artifacts when the number of digits is bigger than 4.

--> Replaced with:
void TM1637::clearDisplay(void) {
	for (int i = 0; i < DIGITS; i++) {
		display(i,0x7f);
	}
}

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
