### ISSUE TITLE
clock/time ":" point

### ISSUE THREAD

**Issue by purevnorov** [Seeed-Studio/Grove_4Digital_Display#17]
I'm using TM1637 time/clock module how can I enable clock/time ":" point

tm1637.point(POINT_ON); or
tm1637.point(true);

is it wrong?

**Comment by ackPeng** [comment]
@purevnorov This doesn't seem to be a problem.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
