### ISSUE TITLE
'class TM1637' has no member named 'set'; did you mean 'setDp'?

### ISSUE THREAD

**Issue by RabbitBot0** [Seeed-Studio/Grove_4Digital_Display#20]
'class TM1637' has no member named 'set'; did you mean 'setDp'?

**Comment by lakshanthad** [comment]
Hello,

I do not see a problem with .cpp and .h files.

https://github.com/Seeed-Studio/Grove_4Digital_Display/blob/master/TM1637.cpp#L293
https://github.com/Seeed-Studio/Grove_4Digital_Display/blob/master/TM1637.h#L68

"set" is included in both.

Could you double-check, please?

**Comment by ackPeng** [comment]
@RabbitBot0 I also checked these two files and found that there is 'set'. Could you please provide more details about this problem?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
