### ISSUE TITLE
update recommendation to displayStr

### ISSUE THREAD

**Issue by cristidr** [Seeed-Studio/Grove_4Digital_Display#8]
Hi ,
I recommend updating to void TM1637::displayStr(**const** char str[], uint16_t loop_delay) .. const char.
It will expand the possibilities( like using from String.c_str,etc), and actual correctness of the code. 
Keep the good work.

**Comment by Pillar1989** [comment]
@cristidr I don't quite understand what you mean. Could you send a PR to explain your idea?

**Comment by Pillar1989** [comment]
Close the problem, and if you need to discuss it again, open it again.
